### ISSUE TITLE
确认下是否合并web UI的代码

### ISSUE THREAD

**Issue by tumuyan** [Ferrocene-Official/VTB-statistics#2]
我使用gradio部分重构了代码，实现了web UI。
大致效果如下，问下你的意见要不要合并到这个仓库。
因为我打算部署到huggingface上，hf同样有git仓库。如果不合并，我就直接移除原先的GUI代码了。

![image](https://user-images.githubusercontent.com/3126801/204119056-0272aca9-97d1-42f8-a1bb-3ae2e00d1d57.png)

![image](https://user-images.githubusercontent.com/3126801/204119053-b9eef072-2ac4-4792-b2cf-17d86d241961.png)

**Comment by tumuyan** [comment]
https://huggingface.co/spaces/tumuyan/DanmuAnalyse

我已经部署到hf了

**Comment by Ferrocene-Official** [comment]
感谢改进，网页形式对一般使用者会更方便，可以合并到这里
